language: ruby
rvm:
  - 1.9.3
  - 2.1.6
  - 2.2.2
  - rbx-2
  - ruby-head
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake test
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
